name: Auto Release

on:
  push:
    branches:
      - main
  schedule:
    # Run every Sunday at 7 AM UTC
    - cron: '0 7 * * 0'
  workflow_dispatch: # Allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to allow version bumping

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install bump2version
      - name: Install bump2version
        run: pip install bump2version

      # Step 4: Bump the version
      - name: Bump version
        run: bump2version minor

      # Step 5: Commit the version change
      - name: Commit version change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add VERSION
          git commit -m "Bump version to $(cat VERSION)"
          git push

      # Step 6: Create a GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(cat VERSION)
          release_name: Release v$(cat VERSION)
          draft: false
          prerelease: false